name: Deploy Sullivan via Shared Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      action_type:
        description: "Action to perform"
        required: true
        type: choice
        options:
          - deploy
          - restart
          - destroy
          - health-check
        default: deploy

jobs:
  get-jump-host-ip:
    name: Get Jump Host IP
    runs-on: ubuntu-latest
    outputs:
      jump_host_ip: ${{ steps.get-ip.outputs.jump_host_ip }}
    steps:
      - name: Install Linode CLI
        run: pip install linode-cli

      - name: Get Nginx Server IP
        id: get-ip
        env:
          LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}
        run: |
          export LINODE_CLI_TOKEN="${{ secrets.LINODE_CLI_TOKEN }}"
          SERVER_LABEL="nginx"
          SERVER_INFO=$(linode-cli linodes list --label "$SERVER_LABEL" --text --no-headers || true)
          if [[ -n "$SERVER_INFO" ]]; then
            SERVER_ID=$(echo "$SERVER_INFO" | cut -f1)
            IP_INFO=$(linode-cli linodes view "$SERVER_ID" --text --no-headers)
            JUMP_HOST_IP=$(echo "$IP_INFO" | cut -f7)
            if [[ -z "$JUMP_HOST_IP" || "$JUMP_HOST_IP" == "null" ]]; then
              IP_INFO_ALT=$(linode-cli linodes ips-list "$SERVER_ID" --text --no-headers)
              JUMP_HOST_IP=$(echo "$IP_INFO_ALT" | head -1 | cut -f1)
            fi
            echo "jump_host_ip=$JUMP_HOST_IP" >> $GITHUB_OUTPUT
          else
            echo "❌ No server found with label: $SERVER_LABEL"
            exit 1
          fi

  deploy:
    name: Deploy Sullivan (home)
    uses: nuniesmith/actions/.github/workflows/deploy.yml@main
    needs: get-jump-host-ip
    with:
      service_name: 'sullivan'
      action_type: ${{ inputs.action_type || 'deploy' }}
      deployment_mode: 'home'
      home_target_host: 'sullivan'
      home_service_user: 'sullivan_user'
      home_repo_url: 'https://github.com/nuniesmith/sullivan.git'
      jump_host: ${{ needs.get-jump-host-ip.outputs.jump_host_ip }}
      domain_suffix: '7gram.xyz'
    secrets:
      LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}
      SERVICE_ROOT_PASSWORD: ${{ secrets.SERVICE_ROOT_PASSWORD }}
      ACTIONS_USER_PASSWORD: ${{ secrets.ACTIONS_USER_PASSWORD }}
      JORDAN_PASSWORD: ${{ secrets.JORDAN_PASSWORD }}
      TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
      TAILSCALE_TAILNET: ${{ secrets.TAILSCALE_TAILNET }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
      SERVICE_USER_PASSWORD: ${{ secrets.SERVICE_USER_PASSWORD }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      HOME_ROOT_SSH_KEY: ${{ secrets.HOME_ROOT_SSH_KEY }}